#!/bin/bash 

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2013 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Remove a task from the specified queue                                       #
#                                                                              #
# 1 = queue                                                                    #
#                                                                              #
################################################################################

progname=${0%-*}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       sqs-remove - removes a task from a queue.

SYNOPSIS
       sqs remove QUEUE ID

DESCRIPTION
       Removes task TASK from the given queue QUEUE.
       This command only removes waiting tasks. To terminate active tasks
       use 'sqs kill QUEUE ID'.

OPTIONS
       -h, --help
           Print this help and exit.

   Exit status
       0  if OK,
       1  else.

AUTHOR
       Written by Thomas Lauf (lauf.thomas@tngtech.com)

SQS
       Part of the sqs suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "Remove a task from a queue."
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "Unknown option '${1}'"
      ;;
    *)
      if [ -z "${queue}" ] ; then
	    queue=${1}
      elif [ -z "${id}" ] ; then
	    id=$*
      fi
  esac
  shift
done

###############################################################################
if [[ -z "${queue}" || -z "${id}" ]] ; then
  abort "sqs-remove: wrong argument count: ${queue} ${id}"
fi

if [ ! -d ${vardir} ] ; then
  abort "sqs-remove: cannot access vardir '${vardir}'"
fi

queuedir=${vardir}/${queue}

if [ ! -d ${queuedir} ] ; then
  abort "sqs-remove: queue '${queue}' does not exist"
fi

key=$(hostname).$$
sqsguard lock ${queuedir} $key || abort "sqs-remove: cannot lock queue ${queue}"

info "sqs-remove: remove task ${id} from queue '${queue}'"
rm ${queuedir}/wait/${id} || { sqsguard unlock ${queuedir} ${key}; abort "sqs-remove: cannot remove task ${id} from queue '${queue}'"; }

sqsguard unlock ${queuedir} ${key} || abort "sqs-remove: cannot unlock queue ${queue}"

exit ${E_SUCCESS}

### EOF
