#!/bin/bash 

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2013 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

progname=${0%-*}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       ${0##*/} - adds a task to a queue.

SYNOPSIS
       ${0##*/} QUEUE TASK

DESCRIPTION
       Adds task TASK to the given queue QUEUE.

   Exit status
       0  if OK,
       1  else.

AUTHOR
       Written by Thomas Lauf (lauf.thomas@tngtech.com)

SQS
       Part of the sqs suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "Add a task to a queue."
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "Unknown option '${1}'"
      ;;
    *)
      if [ -z "${queue}" ] ; then
	    queue=${1}
      elif [ -z "${task}" ] ; then
	    task=$*
      fi
  esac
  shift
done

###############################################################################
if [[ -z "${queue}" || -z "${task}" ]] ; then
  abort "sqs-add: wrong argument count: ${queue} ${task}"
fi

if [ ! -d ${vardir} ] ; then
  abort "sqs-add: cannot access vardir '${vardir}'"
fi

if [ ! -d ${vardir}/${queue} ] ; then
  abort "sqs-add: queue '${queue}' does not exist"
fi

i=$(cat ${vardir}/${queue}/info/ntask)
((i++))
echo "sqs-add: add task ${i} to queue '${queue}': '${task}'"
echo ${task} > ${vardir}/${queue}/wait/${i}
echo ${i}    > ${vardir}/${queue}/info/ntask

