#!/bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Sets a value for the specified host in the specified file                    #
#                                                                              #
# WARNING: script does not lock <queue>! Locking and release of the            #
#          queue has to be done by the caller!                                 #
#                                                                              #
# 1 = filename (e.g. <queue>/info/nproc)                                       #
# 2 = hostname                                                                 #
# 3 = default value                                                            #
#                                                                              #
################################################################################

progname=${0}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       sqs-get - Get a host setting from a queue info file.

SYNOPSIS
       sqs-get [OPTION]... FILE HOST [DEFAULT]

DESCRIPTION
       Reads the value for HOST from the given queue info FILE and prints it
       on the standard output. If HOST is not found in FILE, DEFAULT is
       printed instead (or nothing if DEFAULT is omitted).

       This is an internal helper used by the SQS runner and dispatcher; it
       does not lock the queue and is not meant to be called directly.

OPTIONS
       -h, --help
           Print this help and exit.

   Exit status
       0  if OK,
       2  if FILE does not exist.

AUTHOR
       Written by Thomas Lauf (lauf.thomas@tngtech.com)

SQS
       Part of the sqs suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "Get a host setting from a queue info file."
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "Unknown option '${1}'"
      ;;
    *)
      if [ -z "${file}" ] ; then
        file=${1}
      elif [ -z "${host}" ] ; then
	host=${1}
      else
	default=${1}
      fi
  esac
  shift
done

###############################################################################
if [ ! -e ${file} ] ; then
  echo "sqs-get: Error, invalid filename '${file}'"
  exit 2
fi

value=$(grep ${host} ${file} 2>/dev/null)

if [ "x${value}" = "x" ] ; then
  echo ${default}
else
  echo ${value#*:}
fi

exit 0

### EOF
