#!/bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Initializes a new queue directory.                                           #
#                                                                              #
# WARNING: script does not lock <vardir>! Locking and release of the           #
#          directory containing the queues has to be done by the caller!       #
#                                                                              #
# Parameters:                                                                  #
# 1 = name of the queue                                                        #
#                                                                              #
# Returns                                                                      #
#  0  on success                                                               #
#  1  if queue already exists                                                  #
# -1  on failure                                                               #
#                                                                              #
################################################################################

E_SUCCESS=0
E_EXISTS=1
E_FAILURE=-1

progname=${0}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       ${0##*/} - <short description>

SYNOPSIS
       ${0##*/} [OPTION]... [ARGUMENT]...

DESCRIPTION
       Initialize a SQS queue. Queues are created in the configured directory.
       You can query this by calling 'sqs config get vardir .'

       WARNING: The script does not lock the queue directory! Concurrent
                access to the queue directory is risky then!

   Exit status
       0  if OK,
       1  else.

AUTHOR
       Written by Thomas Lauf (lauf.thomas@tngtech.com)

SQS
       Part of the sqs suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "Initialize a queue."
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "sqs-init: unknown option '${1}'"
      ;;
    *)
      queue=${1}
  esac
  shift
done

###############################################################################
if [ -z "${queue}" ] ; then
  abort "sqs-init: no queue given!"
fi

vardir=$(sqs-config get vardir .) 

if [ "x${vardir}" == "x." ] ; then
  abort "sqs-init: no vardir!"
fi

# checking whether queue already exists
if [ -e "${vardir}/${queue}" ] ; then
  if [ "x${verbose}" = "xyes" ] ; then
    echo "sqs-init: queue '${queue}' already exists!"
  fi
  exit ${E_EXISTS}
fi

# creating queue if non-existent
if [ "x${verbose}" = "xyes" ] ; then
  echo "sqs-init: queue does not exist, creating new queue!"
fi

mkdir ${vardir}/${queue} || exit ${E_FAILURE}

# creating subfolders
mkdir ${vardir}/${queue}/wait || exit ${E_FAILURE}
mkdir ${vardir}/${queue}/exec || exit ${E_FAILURE}
mkdir ${vardir}/${queue}/proc || exit ${E_FAILURE}
mkdir ${vardir}/${queue}/info || exit ${E_FAILURE}

# creating info files
touch ${vardir}/${queue}/info/hosts  || exit ${E_FAILURE}
touch ${vardir}/${queue}/info/nproc  || exit ${E_FAILURE}
touch ${vardir}/${queue}/info/nice   || exit ${E_FAILURE}
touch ${vardir}/${queue}/info/ionice || exit ${E_FAILURE}

# filling in default values
echo "-1"                 > ${vardir}/${queue}/info/ntask
echo "master=$(hostname)" > ${vardir}/${queue}/info/options
echo "halt"               > ${vardir}/${queue}/info/state

exit ${E_SUCCESS}
