#!/bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

progname=${0%-*}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       ${0##*/} - <short description>

SYNOPSIS
       ${0##*/} [OPTION]... [ARGUMENT]...

DESCRIPTION
       Closes (i.e. removes) the given queue.

   Exit status
       0  if OK,
       1  else.

AUTHOR
       Written by Thomas Lauf (lauf.thomas@tngtech.com)

SQS
       Part of the sqs suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "Close a queue."
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "Unknown option '${1}'"
      ;;
    *)
      queue=${1%/}
      ;;
  esac
  shift
done

###############################################################################
key="$(hostname).$$"

vardir=$(sqs-config get vardir .)
queuedir=${vardir}/${queue}
parent=${queuedir%/*}

if ! [ -d ${queuedir} ] ; then
  echo "sqsclose: path '${queuedir}' does not point to a directory"
  exit 2
fi

if ! [ -e ${queuedir} ] ; then
  echo "sqsclose: queue '${queue}' does not exist"
  exit 3
fi

sqslock ${parent} ${key} || exit $?

sqslock ${queuedir} ${key} || { sqsunlock ${parent} ${key} ; exit 3 ; }

rm -rf ${queuedir}

sqsunlock ${parent} ${key} || exit $?

exit 0

### EOF
