#!/bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Sets a value for the specified host in the specified file                    #
#                                                                              #
# WARNING: script does not lock <queue>! Locking and release of the            #
#          queue has to be done by the caller!                                 #
#                                                                              #
# 1 = filename (e.g. <queue>/info/nproc)                                       #
# 2 = hostname                                                                 #
# 3 = value                                                                    #
#                                                                              #
################################################################################

progname=${0}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       ${0##*/} - <short description>

SYNOPSIS
       ${0##*/} [OPTION]... [ARGUMENT]...

DESCRIPTION
       Place a description of the command here. Followed by details about the
       individual options

       -<short-option>, --<long-option>
              Description of the specific option

   Exit status
       0  if OK,
       1  else.

AUTHOR
       Written by Thomas Lauf (lauf.thomas@tngtech.com)

SQS
       Part of the sqs suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "Set setting for host."
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "Unknown option '${1}'"
      ;;
    *)
      if [ -z "${file}" ] ; then
	file=${1}
      elif [ -z "${host}" ] ; then
	host=${1}
      else
	value=${1}
      fi
  esac
  shift
done

###############################################################################
if [ ! -e ${file} ] ; then
  echo "sqs-set: Error, invalid filename '${file}'"
  exit 2
fi

grep -v ${host} ${file} > ${file}.tmp 
echo "${host}:${value}" >> ${file}.tmp || exit $?
mv -f ${file}.tmp ${file}              || exit $?

exit 0

### EOF
