#! /bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Get and set configuration settings                                           #
# The config file has to be located in the                                     #
# same directory as this script!                                               #
# Configuration are stored as bash variables, i.e.                             #
# in the format <key>=<value>                                                  #
#                                                                              #
# USAGE:                                                                       #
#   sqs-config get KEY DEF                                                     #
#   sqs-config set KEY VAL                                                     #
#                                                                              #
################################################################################

# exit codes
E_SUCCESS=0
E_FAILURE=1

cfgfile=${0%/*}/sqsconf

if [ ! -e ${cfgfile} ] ; then
  echo "sqs-config: cannot access config file (${cfgfile})" >&2
  exit ${E_FAILURE}
fi

if [ $# -ne 3 ] ; then
  echo "sqs-config: wrong argument count! ($*)" >&2
  exit ${E_FAILURE}
fi

cmd=${1}
key=${2}

if [ "x${cmd}" = "xget" ] ; then
  # retrieve a value from the config file
  def=${3}
  val=$(grep ${key} ${cfgfile} 2>/dev/null)
  if [ "x${val}" = "x" ] ; then
    echo ${def}
  else
    echo ${val#*=}
  fi
elif [ "x${cmd}" = "xset" ] ; then
  # set a value in the config file
  val=${3}
  grep -v ${key} ${cfgfile} > ${cfgfile}.tmp 
  echo "${key}=${val}" >> ${cfgfile}.tmp || exit $?
  mv -f ${cfgfile}.tmp ${cfgfile}        || exit $?
else
  # invalid command
  echo "sqs-config: unknown command '${cmd}'" >&2
  exit ${E_FAILURE}
fi

exit ${E_SUCCESS}

### EOF
