#!/bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Closes (i.e. removes) the given queue                                        #
#                                                                              #
# 1 = queue name                                                               #
#                                                                              #
################################################################################

progname=${0%-*}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       ${0##*/} - <short description>

SYNOPSIS
       ${0##*/} [OPTION]... [ARGUMENT]...

DESCRIPTION
       Place a description of the command here. Followed by details about the
       individual options

       -<short-option>, --<long-option>
              Description of the specific option

   Exit status
       0  if OK,
       1  else.

AUTHOR
       Written by <your name> (<your email>)

<CLI>
       Part of the <cli> suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "This is an example command"
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "Unknown option '${1}'"
      ;;
  esac
  shift
done

###############################################################################
if [ $# -ne 1 ] ; then
  echo "sqsclose: wrong argument count! ($*)"
  exit 1
fi

key="$(hostname).$$"
queue=${1%/}

if ! [ -d ${queue} ] ; then
  echo "sqsclose: path '${queue}' does not point to a directory"
  exit 2
fi

if ! [ -e ${queue} ] ; then
  echo "sqsclose: queue '${queue}' does not exist"
  exit 3
fi

parent=${queue%/*}

sqslock ${parent} ${key} || exit $?

sqslock ${queue} ${key} || { sqsunlock ${parent} ${key} ; exit 3 ; }

rm -rf ${queue}

sqsunlock ${parent} ${key} || exit $?

exit 0

### EOF
