#!/bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

progname=${0%-*}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       sqs-close - Close a queue.

SYNOPSIS
       sqs close [OPTION]... [QUEUE]

DESCRIPTION
       Closes (i.e. removes) the given queue QUEUE.

OPTIONS
       -h, --help
           Print this help and exit.

   Exit status
       0  if OK,
       1  else.

AUTHOR
       Written by Thomas Lauf (lauf.thomas@tngtech.com)

SQS
       Part of the sqs suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "Close a queue."
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "Unknown option '${1}'"
      ;;
    *)
      queue=${1}
      ;;
  esac
  shift
done

###############################################################################
if [ -z "${queue}" ] ; then
  abort "sqs-close: no queue given"
fi

if [ ! -d ${vardir} ] ; then
  abort "sqs-start: cannot access vardir '${vardir}'"
fi

key="$(hostname).$$"
sqsguard lock ${vardir} ${key} || abort "sqs-close: cannot lock '${vardir}'"

queuedir=${vardir}/${queue}

if [ ! -d ${queuedir} ] ; then
  abort "sqs-close: queue '${queue}' does not exist"
fi


sqsguard lock ${queuedir} ${key} || { sqsguard unlock ${vardir} ${key} ; abort "sqs-close: cannot lock '${queuedir}'" ; }

# check whether queue is on halt? processes running?
rm -rf ${queuedir}

sqsguard unlock ${vardir} ${key} || abort "sqs-close: cannot unlock '${vardir}'"

exit ${E_SUCCESS}

### EOF
