#!/bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Initializes a new queue directory.                                           #
#                                                                              #
# WARNING: script does not lock <vardir>! Locking and release of the           #
#          directory containing the queues has to be done by the caller!       #
#                                                                              #
# Parameters:                                                                  #
# 1 = name of the queue                                                        #
#                                                                              #
# Returns                                                                      #
#  0  on success                                                               #
#  1  if queue already exists                                                  #
# -1  on failure                                                               #
#                                                                              #
################################################################################

E_SUCCESS=0
E_EXISTS=1
E_FAILURE=-1

if [ $# -ne 1 ] ; then
  echo "sqs-init: wrong argument count! ($*)"
  exit 1
fi

vardir=$(sqs-config get vardir "")

if [ "x${vardir}" == "x" ] ; then
  echo "sqs-init: no vardir!"
  exit ${E_FAILURE}
fi

queue=${1}

# checking whether queue already exists
if [ -e "${vardir}/${queue}" ] ; then
  if [ "x${verbose}" = "xyes" ] ; then
    echo "sqs-init: queue '${queue}' already exists!"
  fi
  exit ${E_EXISTS}
fi

# creating queue if non-existent
if [ "x${verbose}" = "xyes" ] ; then
  echo "sqs-init: queue does not exist, creating new queue!"
fi

mkdir ${vardir}/${queue} || exit ${E_FAILURE}

# creating subfolders
mkdir ${vardir}/${queue}/wait || exit ${E_FAILURE}
mkdir ${vardir}/${queue}/exec || exit ${E_FAILURE}
mkdir ${vardir}/${queue}/proc || exit ${E_FAILURE}
mkdir ${vardir}/${queue}/info || exit ${E_FAILURE}

# creating info files
touch ${vardir}/${queue}/info/hosts  || exit ${E_FAILURE}
touch ${vardir}/${queue}/info/nproc  || exit ${E_FAILURE}
touch ${vardir}/${queue}/info/nice   || exit ${E_FAILURE}
touch ${vardir}/${queue}/info/ionice || exit ${E_FAILURE}

# filling in default values
echo "-1"                 > ${vardir}/${queue}/info/ntask
echo "master=$(hostname)" > ${vardir}/${queue}/info/options
echo "halt"               > ${vardir}/${queue}/info/state

exit ${E_SUCCESS}
