#! /bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 2012 by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Get and set configuration settings                                           #
# The config file has to be located in the                                     #
# same directory as this script!                                               #
# Configuration are stored as bash variables, i.e.                             #
# in the format <key>=<value>                                                  #
#                                                                              #
# USAGE:                                                                       #
#   sqs-config get KEY DEF                                                     #
#   sqs-config set KEY VAL                                                     #
#                                                                              #
################################################################################

# exit codes
E_SUCCESS=0
E_FAILURE=1

progname=${0}
progdir=${progname%/*}
progbase=${progname#${progdir}}
progbase=${progbase%%-*}

source ${progdir}/${progbase}common

function print_help()
{
  # print help about this command
  cat <<EOF
NAME
       ${0##*/} - <short description>

SYNOPSIS
       ${0##*/} [OPTION]... [ARGUMENT]...

DESCRIPTION
       Place a description of the command here. Followed by details about the
       individual options

       -<short-option>, --<long-option>
              Description of the specific option

   Exit status
       0  if OK,
       1  else.

AUTHOR
       Written by <your name> (<your email>)

<CLI>
       Part of the <cli> suite
EOF
}

function print_descr()
{
  # a one-liner about this command
  echo "This is an example command"
}

# parse options/arguments
until [ -z "${1}" ] ; do
  case "${1}" in
    --describe)
      print_descr
      exit
      ;;
    --help)
      print_help
      exit
      ;;
    -*)
      abort "Unknown option '${1}'"
      ;;
  esac
  shift
done

###############################################################################cfgfile=${0%/*}/sqsconf

if [ ! -e ${cfgfile} ] ; then
  echo "sqs-config: cannot access config file (${cfgfile})" >&2
  exit ${E_FAILURE}
fi

if [ $# -ne 3 ] ; then
  echo "sqs-config: wrong argument count! ($*)" >&2
  exit ${E_FAILURE}
fi

cmd=${1}
key=${2}

if [ "x${cmd}" = "xget" ] ; then
  # retrieve a value from the config file
  def=${3}
  val=$(grep ${key} ${cfgfile} 2>/dev/null)
  if [ "x${val}" = "x" ] ; then
    echo ${def}
  else
    echo ${val#*=}
  fi
elif [ "x${cmd}" = "xset" ] ; then
  # set a value in the config file
  val=${3}
  grep -v ${key} ${cfgfile} > ${cfgfile}.tmp 
  echo "${key}=${val}" >> ${cfgfile}.tmp || exit $?
  mv -f ${cfgfile}.tmp ${cfgfile}        || exit $?
else
  # invalid command
  echo "sqs-config: unknown command '${cmd}'" >&2
  exit ${E_FAILURE}
fi

exit ${E_SUCCESS}

### EOF
