#!/bin/bash

################################################################################
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Retrieves value for an option from <queue>/info/options.                     #
#                                                                              #
# WARNING: script does not lock <queue>! Locking and release of the            #
#          queue has to be done by the caller!                                 #
#                                                                              #
# 1 = queue path                                                               #
# 2 = key to be queried                                                        #
# 3 = default value                                                            #
#                                                                              #
# The value associated to the key or the given default value                   #
# is returned to stdout                                                        #
#                                                                              #
################################################################################

if [ $# -ne 3 ] ; then
  echo "sqsgetopt: wrong argument count! ($*)" > 2
  exit 1
fi

queue=${1}
key=${2}
default=${3}

value=$(grep ${key} ${queue}/info/options 2>/dev/null)

if [ "x${value}" = "x" ] ; then
  echo ${default}
else
  echo ${value#*=}
fi

exit 0

### EOF