#!/bin/bash

#
# Helper script for the SQS
# Retrieves value for an option from <queue>/info/options.
#
# WARNING: script does not lock <queue>! Locking and release of the
#          queue has to be done by the caller!
#
# 1 = queue name
# 2 = key to be queried
# 3 = default value
#
# The value associated to the key or the given default value 
# is returned to stdout
#

if [ $# -ne 3 ] ; then
  echo "sqsgetopt: wrong argument count! ($*)"
  exit 1
fi

queue=${1}
key=${2}
default=${3}

value=$(grep ${key} ${queue}/info/options 2>/dev/null)

if [ "x${value}" = "x" ] ; then
	echo ${default}
else
	echo ${value#*=}
fi

exit 0

### EOF