#!/bin/bash

#
# Helper script for the SQS
# Retrieves sucessively tasks from queue and waits for their completion
#

if [ $# -ne 1 ] ; then
	echo "sqsrunner: wrong argument count!"
	exit 1
fi

queue=$1

if ! [ -e ${queue} ] ; then
  echo "sqsrunner: queue '${queue}' does not exist!"
	exit 2
fi

echo "idle" > ${queue}/proc/$$

while [ true ] ; do
  sqslock ${queue}
    
  # retrieve first task from queue
  id=`ls ${queue}/wait | grep -v "lockfile" | sort -n | head -n 1`
    
  if [ "${id}" = "" ] ; then
    echo "sqsrunner: no more tasks in list"
    break
  fi

  task=`cat ${queue}/wait/${id}`
  mv -f ${queue}/wait/${id} ${queue}/exec/
  echo "sqsrunner: executing task ${id}: '${task}'"
  echo "${id}" > ${queue}/proc/$$

  sqsunlock ${queue}
    
  # start task
  ${task} &

  # wait for completion
  wait

  echo "idle" > ${queue}/proc/$$
  rm -f ${queue}/exec/${id}

done

sqsunlock ${queue}

rm ${queue}/proc/$$
