#!/bin/bash

#
# Helper script for the SQS
# Retrieves sucessively tasks from queue and waits for their completion
#

source sqsconfig

if [ $# -ne 1 ] ; then
  echo "sqsrunner: wrong argument count!"
  exit 1
fi

queue=${1}

if ! [ -e ${queue} ] ; then
  echo "sqsrunner: queue '${queue}' does not exist!"
  exit 2
fi

while [ true ] ; do
  sqslock ${queue}

  # retrieve number of waiting tasks (ntsk)
  ntsk=`ls ${queue}/wait | wc -w`

  # retrieve number of processes running (nproc)
  nproc=`ls ${queue}/proc | wc -w`

  # quit if ntsk = 0 and nproc > 0
  # also close queue if ntsk = 0 and nproc = 0
  if [ ${ntsk} -eq 0 ] ; then 
    if [ "x${verbose}" = "xyes" ] ; then
      echo "sqsrunner: no more tasks in queue '${queue}'"
    fi

    sqsunlock ${queue}

    if [ ${nproc} -eq 0 ] ; then
      echo "sqsrunner: all processes have finished"
      
      sqslock ${vardir}
      sqslock ${queue}

      echo "sqsrunner: closing queue '${queue}'"
      rm -r ${queue}
      sqsunlock ${vardir}
    fi
    
    break
  fi

  # retrieve number of maximum allowed processes (nmax)
  nmax=`cat ${queue}/info/nproc`

  # add coming process to number of processes
  ((nproc++))

  # fork if nproc < nmax
  if [ "${nproc}" -lt "${nmax}" ] ; then
    echo "${nproc} < ${nmax}"
    sqsrunner ${queue} &
  elif [  "${nproc}" -gt "${nmax}" ] ; then 
    echo "${nproc} >= ${nmax}"
    sqsunlock ${queue}
    break
  fi
    
  # retrieve first task from queue
  id=`ls ${queue}/wait | sort -n | head -n 1`
    
  if [ "${id}" = "" ] ; then
    if [ "x${verbose}" = "xyes" ] ; then
      echo "sqsrunner: no more tasks in list"
    fi
    break
  fi

  task=`cat ${queue}/wait/${id}`
  mv -f ${queue}/wait/${id} ${queue}/exec/

  sqsunlock ${queue}

  if [ "x${verbose}" = "xyes" ] ; then
    echo "sqsrunner: executing task ${id}: '${task}'"
  fi
   
  # start task
  ${task} &
  pid=$!

  echo "${id}" > ${queue}/proc/${pid}

  # wait for completion
  wait ${pid}

  rm -f ${queue}/exec/${id}
  rm -f ${queue}/proc/${pid}
done

### EOF