#!/bin/bash

################################################################################
# SQS - a simple queuing system                                                #
# Copyright (C) 20XX by Thomas Lauf                                            #
#                                                                              #
# This file is part of SQS.                                                    #
#                                                                              #
# SQS is free software: you can redistribute it and/or modify                  #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# SQS is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with SQS.  If not, see <http://www.gnu.org/licenses/>.                 #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
# Helper script for the SQS                                                    #
# Sets a value for the specified host in the specified file                    #
#                                                                              #
# WARNING: script does not lock <queue>! Locking and release of the            #
#          queue has to be done by the caller!                                 #
#                                                                              #
# 1 = filename (e.g. <queue>/info/nproc)                                       #
# 2 = hostname                                                                 #
# 3 = value                                                                    #
#                                                                              #
################################################################################

if [ $# -ne 3 ] ; then
  echo "sqsset: wrong argument count! ($*)" 
  exit 1
fi

file=${1}
host=${2}
value=${3}

if [ ! -e ${file} ] ; then
  echo "sqsset: Error, invalid filename '${file}'"
  exit 2
fi

grep -v ${host} ${file} > ${file}.tmp 
echo "${host}:${value}" >> ${file}.tmp || exit $?
mv -f ${file}.tmp ${file}              || exit $?

exit 0

### EOF
