#! /bin/bash

#
# Helper script for the SQS
# Performs various check on specified host
#
# 1 = hostname
#

E_SUCCESS=0
E_FAILURE=1

if [ $# -ne 1 ] ; then
  echo "sqstest: wrong argument count! ($*)" 
  exit ${E_FAILURE}
fi

hostname=${1}

# Check whether host does exist
echo -n "testing whether host '${hostname}' does exist... "

if ! host ${hostname} > /dev/null 2>&1 ; then
  echo "no"
  echo "sqstest: host ${hostname} does not exist"
  exit ${E_FAILURE}
fi

echo "yes"

# Check whether we can do passwordless connect
echo -n "testing whether we can do passwordless connect on host... "
#if ssh ${hostname} > /dev/null 2>&1 ; then
#  echo "sqstest: host ${hostname} does not exist"
#  exit ${E_FAILURE}
#fi
echo "skipped"

# Check sqs installation on host
echo "testing sqs installation on host..."
binlist="sqs \
         sqsrunner \
         sqsclose \
         sqsconf \
         sqscreate \
         sqslock \
         sqsunlock \
         sqsget \
         sqsset \
         sqsgetopt \
         sqssetopt \
         sqsupdate"

for bin in ${binlist}; do
  echo -n "testing '${bin}'... "
  result=$(ssh ${hostname} which ${bin} > /dev/null 2>&1; echo $?)

  if [ "x${result}" != "x0" ] ; then
    echo "no"
    echo "sqstest: ${bin} not found on ${hostname}"
    exit ${E_FAILURE}
  fi

  echo "yes"
done
echo "sqs installation is identical..."

# Check whether we see the same queue
echo -n "testing whether we see the same queue..."
key=$$
touch $(sqsconf get vardir '')/${key}

result=$(ssh ${hostname} ls $(sqsconf get vardir '')/${key} > /dev/null 2>&1; echo $?)
if [ "x${result}" != "x0" ] ; then
  echo "no"
  echo "sqstest: no access to common queue directory"
  exit ${E_FAILURE}
fi

rm -f $(sqsconf get vardir '')/${key}

echo "yes"

exit ${E_SUCCESS}