#!/bin/bash

#
# Helper script for the SQS
# Unlocks directories
#

if [ $# -ne 1 ] ; then
	echo "sqslock: wrong argument count!"
	exit 1
fi

dir=$1

echo "sqsunlock: unlocking ${dir}"
rm -rf ${dir}/lockfile


