#!/bin/bash

#
# Helper script for the SQS
# Unlocks directories
#

if [ $# -ne 1 ] ; then
  echo "sqslock: wrong argument count! ($*)"
  exit 1
fi

dir=$1

if [ "x${verbose}" = "xyes" ] ; then
  echo "sqsunlock: unlocking ${dir}"
fi
rm -rf ${dir}/lockfile


